# Generated by Django 5.1.2 on 2024-11-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'Color name cannot be blank.', 'unique': 'A color with this name already exists.'}, help_text='The name of the color - must be unique', max_length=50, unique=True, verbose_name='color name')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'db_table': 'vehicle_colors',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='color_name_idx')],
            },
        ),
    ]
