# Generated by Django 5.1.2 on 2024-11-03 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the vehicle model', max_length=100, verbose_name='name')),
                ('manufacturer', models.ForeignKey(help_text='Manufacturer this model belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='models', to='vehicle.manufacturer')),
            ],
            options={
                'verbose_name': 'Vehicle Model',
                'verbose_name_plural': 'Vehicle Models',
                'ordering': ['manufacturer__name', 'name'],
                'unique_together': {('name', 'manufacturer')},
            },
        ),
    ]
