# Generated by Django 5.1.2 on 2024-11-03 11:08

import django.core.validators
import django.db.models.deletion
import vehicle.models.vehicle
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_vehiclemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vin', models.CharField(error_messages={'invalid': 'Enter a valid VIN.', 'unique': 'A vehicle with this VIN already exists.'}, help_text='17-character Vehicle Identification Number', max_length=17, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(17), django.core.validators.MaxLengthValidator(17), django.core.validators.RegexValidator(message='Enter a valid 17-character VIN. Letters I, O, and Q are not allowed.', regex='^[A-HJ-NPR-Z0-9]{17}$')], verbose_name='VIN')),
                ('year_built', models.IntegerField(help_text='Year the vehicle was manufactured', validators=[django.core.validators.MinValueValidator(1886, message='Year must be 1886 or later.'), django.core.validators.MaxValueValidator(vehicle.models.vehicle.get_max_year, message='Year cannot be in the future.')], verbose_name='Year Built')),
                ('nickname', models.CharField(blank=True, help_text='Optional nickname for the vehicle', max_length=100, null=True, verbose_name='Nickname')),
                ('interior_color', models.ForeignKey(help_text='Vehicle interior color', on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_interior_color', to='vehicle.color', verbose_name='Interior Color')),
                ('model', models.ForeignKey(help_text='Vehicle model', on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicle.vehiclemodel', verbose_name='Model')),
                ('outer_color', models.ForeignKey(help_text='Vehicle exterior color', on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_outer_color', to='vehicle.color', verbose_name='Exterior Color')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicles',
                'ordering': ['-year_built', 'model'],
                'indexes': [models.Index(fields=['year_built'], name='vehicle_year_idx'), models.Index(fields=['model'], name='vehicle_model_idx')],
            },
        ),
    ]
