# Generated by Django 5.1.2 on 2024-11-03 11:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the component type (e.g., engine, window)', max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Description of this component type', verbose_name='description')),
            ],
            options={
                'verbose_name': 'Component Type',
                'verbose_name_plural': 'Component Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Name of the component (e.g., front left window, engine, rear right door, etc.)', max_length=200, unique=True, verbose_name='name')),
                ('status', models.FloatField(blank=True, default=0.0, help_text='Current status of the component (0.0-1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Status cannot be less than 0'), django.core.validators.MaxValueValidator(1.0, 'Status cannot be greater than 1')], verbose_name='status')),
                ('component_type', models.ForeignKey(help_text='Type of this component', on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_components', to='vehicle.componenttype', verbose_name='component type')),
                ('vehicle', models.ForeignKey(help_text='Vehicle this component belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='vehicle.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Component',
                'verbose_name_plural': 'Vehicle Components',
                'ordering': ['vehicle', 'component_type__name'],
                'unique_together': {('vehicle', 'component_type')},
            },
        ),
    ]
