# Generated by Django 5.1.2 on 2024-11-17 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_alter_componenttype_name_alter_manufacturer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='country_code',
            field=models.CharField(default='DE', error_messages={'blank': 'Country code cannot be blank.', 'invalid': 'Enter a valid country code (2 uppercase letters).'}, help_text="ISO 3166-1 alpha-2 country code (e.g., 'DE' for Germany)", max_length=2, validators=[django.core.validators.RegexValidator(message='Country code must be exactly 2 uppercase letters.', regex='^[A-Z]{2}$')], verbose_name='country code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the manufacturer', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='website_url',
            field=models.URLField(blank=True, error_messages={'invalid': 'Enter a valid URL.'}, help_text='Official manufacturer website URL', max_length=255, null=True, validators=[django.core.validators.URLValidator()], verbose_name='website URL'),
        ),
        migrations.AddIndex(
            model_name='manufacturer',
            index=models.Index(fields=['country_code'], name='manufacturer_country_idx'),
        ),
    ]
