# Generated by Django 5.1.2 on 2024-11-11 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_alter_componenttype_name_alter_manufacturer_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehiclecomponent',
            unique_together={('vehicle', 'component_type', 'name')},
        ),
    ]
