# Generated by Django 5.1.2 on 2024-11-17 13:01

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_manufacturer_country_code_manufacturer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='description',
            field=models.TextField(blank=True, help_text='Additional details about the color', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Color in hexadecimal format (e.g., #FF0000 for red)', image_field=None, max_length=25, samples=['#FF0000', '#00FF00', '#0000FF', '#FFFFFF', '#000000', '#808080', '#A9A9A9'], verbose_name='color code'),
        ),
        migrations.AddField(
            model_name='color',
            name='is_metallic',
            field=models.BooleanField(default=False, help_text='Indicates if the color has a metallic finish', verbose_name='metallic finish'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='country_code',
            field=models.CharField(error_messages={'blank': 'Country code cannot be blank.', 'invalid': 'Enter a valid country code (2 uppercase letters).'}, help_text="ISO 3166-1 alpha-2 country code (e.g., 'DE' for Germany)", max_length=2, validators=[django.core.validators.RegexValidator(message='Country code must be exactly 2 uppercase letters.', regex='^[a-zA-Z]{2}$')], verbose_name='country code'),
        ),
    ]
