# Generated by Django 5.1.2 on 2024-11-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_modelcomponent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelcomponent',
            name='is_required',
        ),
    ]
