# Generated by Django 5.1.2 on 2024-11-18 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_remove_modelcomponent_is_required'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modelcomponent',
            unique_together={('model', 'name', 'component_type')},
        ),
    ]
