# Generated by Django 5.1.2 on 2024-11-18 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_alter_modelcomponent_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehiclecomponent',
            unique_together={('vehicle', 'component_type', 'name')},
        ),
    ]
