# Generated by Django 5.1.2 on 2024-11-21 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0013_alter_vehiclecomponent_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(blank=True, error_messages={'invalid': 'Select a valid vehicle model.'}, help_text='Owner of the vehicle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
