# Generated by Django 5.1.2 on 2024-11-22 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0014_vehicle_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-year_built', 'model'], 'permissions': (('is_owner', 'The owner can control everything'),), 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
    ]
