# Generated by Django 5.1.2 on 2024-11-22 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0015_alter_vehicle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-year_built', 'model'], 'permissions': (('is_owner', 'Can control everything'),), 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
    ]
