# Generated by Django 5.1.2 on 2024-11-23 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_alter_vehiclecomponent_unique_together'),
        ('vehicle', '0016_alter_vehicle_options'),
    ]

    operations = [
    ]
