# Generated by Django 5.1.3 on 2024-12-01 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0019_alter_vehiclecomponent_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentpermission',
            options={'ordering': ['-created'], 'permissions': (('can_grant_access', 'Can grant component access'), ('can_revoke_access', 'Can revoke component access')), 'verbose_name': 'Component Permission', 'verbose_name_plural': 'Component Permissions'},
        ),
        migrations.RenameIndex(
            model_name='componentpermission',
            new_name='component_perm_comp_user_idx',
            old_name='vehicle_com_compone_ce76eb_idx',
        ),
        migrations.RenameIndex(
            model_name='componentpermission',
            new_name='component_perm_valid_until_idx',
            old_name='vehicle_com_valid_u_5ce588_idx',
        ),
        migrations.AlterField(
            model_name='componentpermission',
            name='component',
            field=models.ForeignKey(help_text='Component this permission applies to', on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='vehicle.vehiclecomponent', verbose_name='component'),
        ),
        migrations.AlterField(
            model_name='componentpermission',
            name='granted_by',
            field=models.ForeignKey(help_text='User who granted this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='granted by'),
        ),
        migrations.AlterField(
            model_name='componentpermission',
            name='permission_type',
            field=models.CharField(choices=[('read', 'Read Only'), ('write', 'Read & Write')], help_text='Level of access granted', max_length=5, verbose_name='permission type'),
        ),
        migrations.AlterField(
            model_name='componentpermission',
            name='user',
            field=models.ForeignKey(help_text='User receiving the permission', on_delete=django.db.models.deletion.CASCADE, related_name='component_permissions', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='componentpermission',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='When this permission expires (optional)', null=True, verbose_name='valid until'),
        ),
    ]
