# Generated by Django 5.1.4 on 2025-01-06 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_companion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year_built',
            field=models.IntegerField(error_messages={'invalid': 'Enter a valid year.', 'null': 'Year built is required.'}, help_text='Year the vehicle was manufactured', validators=[django.core.validators.MinValueValidator(1886, message='Year must be 1886 or later.'), django.core.validators.MaxValueValidator(2026, message='Year cannot be in the future.')], verbose_name='Year Built'),
        ),
    ]
