# Generated by Django 5.1.4 on 2024-12-17 08:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_companion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='nickname',
        ),
        migrations.CreateModel(
            name='VehicleUserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(error_messages={'max_length': 'Nickname cannot be longer than 100 characters.'}, help_text='Personal nickname for the vehicle', max_length=100, validators=[django.core.validators.RegexValidator(message='Nickname can only contain letters, numbers, spaces, and hyphens.', regex='^[a-zA-Z0-9\\s\\-]*$')], verbose_name='nickname')),
                ('exterior_color', models.ForeignKey(blank=True, help_text='User-specific exterior color preference', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='car_companion.color', verbose_name='personal exterior color')),
                ('interior_color', models.ForeignKey(blank=True, help_text='User-specific interior color preference', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='car_companion.color', verbose_name='personal interior color')),
                ('user', models.ForeignKey(help_text='User who set these preferences', on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_preferences', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('vehicle', models.ForeignKey(help_text='Vehicle these preferences belong to', on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='car_companion.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle User Preferences',
                'verbose_name_plural': 'Vehicle User Preferences',
                'db_table': 'vehicle_user_preferences',
                'ordering': ['vehicle', 'user'],
                'unique_together': {('vehicle', 'user')},
            },
        ),
    ]
