# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: 'Build and deploy Python app to Azure Web App: car-companion-dev'

on:
  push:
    branches:
    - development
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.12'
    
    - name: Install poetry
      uses: abatilo/actions-poetry@v2
    
    - name: Make Oryx happy with requirements.txt
      working-directory: ${{ inputs.function_directory }}
      run: |
        poetry export --without-hashes --format=requirements.txt > requirements.txt

    - name: Create .env file
      working-directory: ${{ inputs.function_directory }}
      run: |
        echo "SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
        echo "DEBUG=${{ secrets.DJANGO_DEBUG }}" >> .env
        echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> .env
        echo "DB_ENGINE_DEV=${{ secrets.DB_ENGINE_DEV }}" >> .env
        echo "DB_NAME_DEV=${{ secrets.DB_NAME_DEV }}" >> .env
        echo "DB_HOST_DEV=${{ secrets.DB_HOST_DEV }}" >> .env
        echo "DB_PORT_DEV=${{ secrets.DB_PORT_DEV }}" >> .env
        echo "DB_USER_DEV=${{ secrets.DB_USER_DEV }}" >> .env
        echo "DB_PASSWORD_DEV=${{ secrets.DB_PASSWORD_DEV }}" >> .env

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: 'car-companion-dev'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_Development }}
