# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: 'Build and deploy Python app to Azure Web App: car-companion'

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.12'
    
    - name: Install poetry
      uses: abatilo/actions-poetry@v2
    
    - name: Make Oryx happy with requirements.txt
      working-directory: ${{ inputs.function_directory }}
      run: |
        poetry export --without-hashes --format=requirements.txt > requirements.txt

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: 'car-companion'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_Main }}

    - name: Run Health Check
      run: |
        status_code=$(curl -s -o /dev/null -w "%{http_code}" https://car-companion.azurewebsites.net/health/?format=json)
        if [ "$status_code" -ne 200 ]; then
          echo "Health check failed with status $status_code"
          exit 1
        fi